
IF NOT EXISTS (select * from sys.tables where name = 'SECS_Description')
    BEGIN
        CREATE TABLE SECS_Description (
        S  int  NOT NULL ,
        F  int  NOT NULL ,
        Annotation   VARCHAR (50) NOT NULL,
        CONSTRAINT u_Customer_Id UNIQUE (S, F),
        CONSTRAINT pk_Customer_Id PRIMARY KEY (S, F)
        );
INSERT INTO SECS_Description (S, F, Annotation) VALUES (0, 0, 'System_LOG');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 0, 'Not On Line');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 1, 'Are You There?');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 2, 'On Line Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 3, 'Selected Equipment Status Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 4, 'Selected Equipment Status Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 5, 'Formatted Status Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 6, 'Formatted Status Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 7, 'Fixed Form Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 8, 'Fixed Form Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 9, 'Material Transfer Status Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 10, 'Material Transfer Status Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 11, 'Status Variable Namelist Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 12, 'Status Variable Namelist Reply');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 13, 'Establish Communications Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 14, 'Establish Communications Request Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 15, 'Request OFF-LINE');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 16, 'OFF-LINE Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 17, 'Request ON-LINE');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 18, 'ON-LINE Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 19, 'Get Attribute');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 20, 'Attribute Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 21, 'Data Variable (DVVAL) Namelist Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 22, 'Data Variable (DVVAL) Namelist Reply');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 23, 'Collection Event Namelist Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (1, 24, 'Collection Event Namelist Reply');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 1, 'Service Program Load Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 2, 'Service Program Load Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 3, 'Service Program Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 4, 'Service Program Send Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 5, 'Service Program Load Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 6, 'Service Program Load Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 7, 'Service Program Run Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 8, 'Service Program Run Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 9, 'Service Program Results Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 10, 'Service Program Results Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 11, 'Service Program Directory Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 12, 'Service Program Directory Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 13, 'Equipment Constant Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 14, 'Equipment Constant Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 15, 'New Equipment Constant Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 16, 'New Equipment Constant Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 17, 'Date and Time Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 18, 'Date and Time Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 19, 'Reset/Initialize Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 20, 'Reset Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 21, 'Remote Command Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 22, 'Remote Command Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 23, 'Trace Initialize Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 24, 'Trace Initialize Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 25, 'Loopback Diagnostic Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 26, 'Loopback Diagnostic Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 27, 'Initiate Processing Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 28, 'Initiate Processing Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 29, 'Equipment Constant Namelist Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 30, 'Equipment Constant Namelist');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 31, 'Date and Time Set Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 32, 'Date and Time Set Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 33, 'Define Report');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 34, 'Define Report Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 35, 'Link Event Report');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 36, 'Link Event Report Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 37, 'Enable/Disable Event Report');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 38, 'Enable/Disable Event Report Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 39, 'Multi-block Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 40, 'Multi-block Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 41, 'Host Command Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 42, 'Host Command Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 43, 'Configure Spooling');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 44, 'Configure Spooling Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 45, 'Define Variable Limit Attributes');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 46, 'Define Variable Limit Attributes Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 47, 'Variable Limit Attribute Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 48, 'Variable Limit Attribute Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 49, 'Enhanced Remote Command');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (2, 50, 'Enhanced Remote Command Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 1, 'Material Status Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 2, 'Material Status Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 3, 'Time to Completion Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 4, 'Time to Completion Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 5, 'Material Found Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 6, 'Material Found Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 7, 'Material Lost Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 8, 'Material Lost Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 9, 'Matl ID Equate Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 10, 'Matl ID Equate Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 11, 'Matl ID Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 12, 'Matl ID Request Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 13, 'Matl ID Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 14, 'Matl ID Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 15, 'Matls Multi-block Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 16, 'Matls Multi-block Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 17, 'Carrier Action Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 18, 'Carrier Action Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 19, 'Cancel All Carrier Out Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 20, 'Cancel All Carrier Out Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 21, 'Port Group Defn');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 22, 'Port Group Defn Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 23, 'Port Group Action Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 24, 'Port Group Action Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 25, 'Port Action Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 26, 'Port Action Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 27, 'Change Access');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 28, 'Change Access Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 29, 'Carrier Tag Read Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 30, 'Carrier Tag Read Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 31, 'Carrier Tag Write Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 32, 'Carrier Tag Write Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 33, 'Cancel All Pod Out Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 34, 'Cancel All Pod Out Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 35, 'Reticle Transfer Job Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (3, 36, 'Reticle Transfer Job Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 0, 'Abort');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 1, 'Ready to Send Materials');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 2, 'Ready to Send Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 3, 'Send Material');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 5, 'Handshake Complete');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 7, 'Not Ready to Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 9, 'Stuck in Sender');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 11, 'Stuck in Receiver');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 13, 'Send Incomplete Timeout');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 15, 'Material Received');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 17, 'Request to Receive');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 18, 'Request to Receive Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 19, 'Transfer Job Create');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 20, 'Transfer Job Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 21, 'Transfer Job Command');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 22, 'Transfer Job Command Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 23, 'Transfer Command Alert');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 24, 'Transfer Alert Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 25, 'Multi-block Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 26, 'Multi-block Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 27, 'Handoff Ready');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 29, 'Handoff Command');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 31, 'Handoff Command Complete');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 33, 'Handoff Verified');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 35, 'Handoff Cancel Ready');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 37, 'Handoff Cancel Ready Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 39, 'Handoff Halt');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (4, 41, 'Handoff Halt Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 1, 'Alarm Report Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 2, 'Alarm Report Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 3, 'Enable/Disable Alarm Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 4, 'Enable/Disable Alarm Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 5, 'List Alarms Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 6, 'List Alarm Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 7, 'List Enabled Alarm Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 8, 'List Enabled Alarm Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 9, 'Exception Post Notify');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 10, 'Exception Post Confirm');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 11, 'Exception Clear Notify');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 12, 'Exception Clear Confirm');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 13, 'Exception Recover Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 14, 'Exception Recover Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 15, 'Exception Recovery Complete Notify');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 16, 'Exception Recovery Complete Confirm');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 17, 'Exception Recovery Abort Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (5, 18, 'Exception Recovery Abort Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 1, 'Trace Data Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 2, 'Trace Data Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 3, 'Discrete Variable Data Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 4, 'Discrete Variable Data Send Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 5, 'Multi-block Data Send Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 6, 'Multi-block Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 7, 'Data Transfer Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 8, 'Data Transfer Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 9, 'Formatted Variable Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 10, 'Formatted Variable Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 11, 'Event Report Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 12, 'Event Report Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 13, 'Annotated Event Report Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 14, 'Annotated Event Report Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 15, 'Event Report Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 16, 'Event Report Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 17, 'Annotated Event Report Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 18, 'Annotated Event Report Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 19, 'Individual Report Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 20, 'Individual Report Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 21, 'Annotated Individual Report Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 22, 'Annotated Individual Report Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 23, 'Request or Purge Spooled Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 24, 'Request or Purge Spooled Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 25, 'Notification Report Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 26, 'Notification Report Send Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 27, 'Trace Report Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 28, 'Trace Report Send Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 29, 'Trace Report Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (6, 30, 'Trace Report Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 1, 'Process Program Load Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 2, 'Process Program Load Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 3, 'Process Program Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 4, 'Process Program Send Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 5, 'Process Program Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 6, 'Process Program Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 7, 'Process Program ID Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 8, 'Process Program ID Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 9, 'Matl/Process Matrix Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 10, 'Matl/Process Matrix Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 11, 'Matl/Process Matrix Update Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 12, 'Matl/Process Matrix Update Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 13, 'Matl/Process Matrix Delete Entry Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 14, 'Delete Matl/Process Matrix Entry Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 15, 'Matrix Mode Select Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 16, 'Matrix Mode Select Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 17, 'Delete Process Program Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 18, 'Delete Process Program Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 19, 'Current Process Program Dir Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 20, 'Current Process Program Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 21, 'Process Capabilities Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 22, 'Process Capabilities Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 23, 'Formatted Process Program Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 24, 'Formatted Process Program Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 25, 'Formatted Process Program Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 26, 'Formatted Process Program Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 27, 'Process Program Verification Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 28, 'Process Program Verification Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 29, 'Process Program Verification Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 30, 'Process Program Verification Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 31, 'Verification Request Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 32, 'Verification Request Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 33, 'Process Program Available Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 34, 'Process Program Availability Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 35, 'Process Program for MID Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 36, 'Process Program for MID Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 37, 'Large PP Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 38, 'Large PP Send Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 39, 'Large Formatted PP Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 40, 'Large Formatted PP Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 41, 'Large PP Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 42, 'Large PP Req Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 43, 'Large Formatted PP Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (7, 44, 'Large Formatted PP Req Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (8, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (8, 1, 'Boot Program Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (8, 2, 'Boot Program Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (8, 3, 'Executive Program Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (8, 4, 'Executive Program Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (9, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (9, 1, 'Unknown Device ID');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (9, 3, 'Unknown Stream');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (9, 5, 'Unknown Function');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (9, 7, 'Illegal Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (9, 9, 'Transaction Timeout');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (9, 11, 'Data Too Long');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (9, 13, 'Conversation Timeout');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (10, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (10, 1, 'Terminal Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (10, 2, 'Terminal Request Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (10, 3, 'Terminal Display, Single');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (10, 4, 'Terminal Display, Single Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (10, 5, 'Terminal Display, Multi-Block');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (10, 6, 'Terminal Display, Multi-Block Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (10, 7, 'Multi-block Not Allowed');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (10, 9, 'Broadcast');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (10, 10, 'Broadcast Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 0, 'File Transaction Abort (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 1, 'File Access Inquire (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 2, 'File Access Grant (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 3, 'File Write (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 4, 'File Write Acknowledge (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 5, 'File Read Request (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 6, 'File Read Data (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 7, 'File Close (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 9, 'File Delete (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 11, 'File Directory Request (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 12, 'File Directory Data (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 13, 'File Exist? (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (11, 14, 'File Length Data (Obsolete)');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 1, 'Map Setup Data Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 2, 'Map Setup Data Acknowledge');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 3, 'Map Setup Data Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 4, 'Map Setup Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 5, 'Map Transmit Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 6, 'Map Transmit Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 7, 'Map Data Send Type 1');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 8, 'Map Data Ack Type 1');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 9, 'Map Data Send Type 2');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 10, 'Map Data Ack Type 2');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 11, 'Map Data Send Type 3');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 12, 'Map Data Ack Type 3');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 13, 'Map Data Request Type 1');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 14, 'Map Data Type 1');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 15, 'Map Data Request Type 2');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 16, 'Map Data Type 2');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 17, 'Map Data Request Type 3');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 18, 'Map Data Type 3');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (12, 19, 'Map Error Report Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 1, 'Send Data Set Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 2, 'Send Data Set Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 3, 'Open Data Set Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 4, 'Open Data Set Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 5, 'Read Data Set Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 6, 'Read Data Set Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 7, 'Close Data Set Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 8, 'Close Data Set Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 9, 'Reset Data Set Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 10, 'Reset Data Set Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 11, 'Data Set Obj Multi-Block Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 12, 'Data Set Obj Multi-Block Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 13, 'Table Data Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 14, 'Table Data Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 15, 'Table Data Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (13, 16, 'Table Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 1, 'Get Attributes');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 2, 'Attribute Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 3, 'Set Attributes');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 4, 'Set Attributes Reply');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 5, 'Get Type');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 6, 'Type Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 7, 'Get Attribute Names');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 8, 'Attribute Names');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 9, 'Create Obj Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 10, 'Create Obj Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 11, 'Delete Obj Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 12, 'Delete Obj Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 13, 'Object Attach Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 14, 'Object Attach Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 15, 'Attached Obj Action Req.');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 16, 'Attached Obj Action Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 17, 'Supervised Obj Action Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 18, 'Supervised Obj Action Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 19, 'Generic Service Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 20, 'Generic Service Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 21, 'Generic Service Completion');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 22, 'Generic Service Comp Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 23, 'Multi-block Generic Service Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 24, 'Multi-block Generic Service Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 25, 'Service Name Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 26, 'Service Name Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 27, 'Service Parameter Name Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (14, 28, 'Service Parameter Name Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 0, 'Abort Transaction');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 1, 'Recipe Management MBI');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 2, 'Recipe Management MBI Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 3, 'Recipe Namespace Action Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 4, 'Recipe Namespace Action');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 5, 'Recipe Namespace Rename Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 6, 'Recipe Namespace Rename Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 7, 'Recipe Space Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 8, 'Recipe Space Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 9, 'Recipe Status Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 10, 'Recipe Status Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 11, 'Recipe Version Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 12, 'Recipe Version Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 13, 'Recipe Create Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 14, 'Recipe Create Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 15, 'Recipe Store Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 16, 'Recipe Store Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 17, 'Recipe Retrieve Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 18, 'Recipe Retrieve Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 19, 'Recipe Rename Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 20, 'Recipe Rename Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 21, 'Recipe Action Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 22, 'Recipe Action Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 23, 'Recipe Descriptor Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 24, 'Recipe Descriptor Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 25, 'Recipe Parameter Update Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 26, 'Recipe Parameter Update Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 27, 'Recipe Download Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 28, 'Recipe Download Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 29, 'Recipe Verify Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 30, 'Recipe Verify Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 31, 'Recipe Unload Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 32, 'Recipe Unload Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 33, 'Recipe Select Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 34, 'Recipe Select Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 35, 'Recipe Delete Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 36, 'Recipe Delete Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 37, 'DRNS Segment Approve Action Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 38, 'DRNS Segment Approve Action Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 39, 'DRNS Recorder Seg Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 40, 'DRNS Recorder Seg Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 41, 'DRNS Recorder Mod Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 42, 'DRNS Recorder Mod Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 43, 'DRNS Get Change Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 44, 'DRNS Get Change Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 45, 'DRNS Mgr Seg Aprvl Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 46, 'DRNS Mgr Seg Aprvl Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 47, 'DRNS Mgr Rebuild Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 48, 'DRNS Mgr Rebuild Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 49, 'Large Recipe Download Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 50, 'Large Recipe Download Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 51, 'Large Recipe Upload Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 52, 'Large Recipe Upload Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 53, 'Recipe Verification Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (15, 54, 'Recipe Verification Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 0, 'Abort');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 1, 'Process Job Data MBI');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 2, 'PJD MBI Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 3, 'Process Job Create Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 4, 'Process Job Create Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 5, 'Process Job Cmd Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 6, 'Process Job Cmd Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 7, 'Process Job Alert Notify');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 8, 'Process Job Alert Cfm');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 9, 'Process Job Event Notify');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 10, 'Process Job Event Cfm');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 11, 'PRJobCreateEnh');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 12, 'PRJobCreateEnh Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 13, 'PRJobDuplicateCreate');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 14, 'PRJobDuplicateCreate Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 15, 'PRJobMultiCreate');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 16, 'PRJobMultiCreate Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 17, 'PRJobDequeue');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 18, 'PRJobDequeue Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 19, 'PRJob List Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 20, 'PRJob List Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 21, 'PRJob Create Limit Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 22, 'PRJob Create Limit Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 23, 'PRJob Recipe Variable Set');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 24, 'PRJob Recipe Variable Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 25, 'PRJob Start Method Set');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 26, 'PRJob Start Method Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 27, 'Control Job Command');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 28, 'Control Job Command Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 29, 'PRSetMtrlOrder');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (16, 30, 'PRSetMtrlOrder Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 0, 'Abort');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 1, 'Data Report Create Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 2, 'Data Report Create Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 3, 'Data Report Del Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 4, 'Data Report Del Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 5, 'Trace Create Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 6, 'Trace Create Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 7, 'Trace Delete Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 8, 'Trace Delete Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 9, 'Collection Event Link Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 10, 'Collection Event Link Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 11, 'Collection Event Unlink');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 12, 'Collection Event Unlink Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 13, 'Trace Reset Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (17, 14, 'Trace Reset Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 0, 'Abort');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 1, 'Read Attribute Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 2, 'Read Attribute Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 3, 'Write Attribute Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 4, 'Write Attribute Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 5, 'Read Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 6, 'Read Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 7, 'Write Data Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 8, 'Write Data Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 9, 'Read ID Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 10, 'Read ID Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 11, 'Write ID Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 12, 'Write ID Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 13, 'Subsystem Command');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 14, 'Subsystem Command Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 15, 'Read 2D Code Cond Req');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (18, 16, 'Read 2D Code Cond Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 0, 'Abort');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 1, 'Get PDE Directory');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 2, 'PDE Directory Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 3, 'Delete PDE');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 4, 'Delete PDE Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 5, 'Get PDE Header');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 6, 'PDE Header Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 7, 'Get PDE');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 8, 'PDE Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 9, 'Request to Send PDE');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 10, 'Send PDE Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 11, 'Send PDE');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 12, 'Send PDE Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 13, 'PDE Transfer Report');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 14, 'Transfer Report Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 15, 'Resolve PDE Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 16, 'Resolve PDE Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 17, 'Verify PDE');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 18, 'Verification Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 19, 'Multiblock Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (19, 20, 'Multiblock Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 1, 'SetSRO Attributes Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 2, 'SetSRO Attributes Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 3, 'GetOperationIDList Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 4, 'GetOperationIDList Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 5, 'OpenConnectionEvent Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 6, 'OpenConnectionEvent Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 7, 'CloseConnectionEvent Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 8, 'CloseConnectionEvent Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 9, 'ClearOperation Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 10, 'ClearOperation Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 11, 'GetRecipeXIDList Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 12, 'GetRecipeXIDList Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 13, 'DeleteRecipe Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 14, 'DeleteRecipe Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 15, 'WriteRecipe Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 16, 'WriteRecipe Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 17, 'ReadRecipe Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 18, 'ReadRecipe Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 19, 'QueryRecipeXIDList Event Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 20, 'QueryRecipeXIDList Event Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 21, 'QueryRecipe Event Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 22, 'QueryRecipe Event Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 23, 'PostRecipe Event Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 24, 'PostRecipe Event Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 25, 'SetPRC Attributes Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 26, 'SetPRC Attributes Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 27, 'PreSpecifyRecipe Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 28, 'PreSpecifyRecipe Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 29, 'QueryPJRecipeXIDList Event Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 30, 'QueryPJRecipeXIDList Event Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 31, 'Pre-Exe Check Event Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 32, 'Pre-Exe Check Event Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 33, 'PreSpecifyRecipe Event Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (20, 34, 'PreSpecifyRecipe Event Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 1, 'Item Load Inquire');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 2, 'Item Load Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 3, 'Item Send');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 4, 'Item Send Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 5, 'Item Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 6, 'Item Data');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 7, 'Item Type List Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 8, 'Item Type List Result');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 9, 'Supported Item Type List Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 10, 'Supported Item Type List Result');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 11, 'Item Delete');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 12, 'Item Delete Ack');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 13, 'Request Send Permission');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 14, 'Grant Send Permission');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 15, 'Item Request');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 16, 'Item Request Grant');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 17, 'Send Item Part');
INSERT INTO SECS_Description (S, F, Annotation) VALUES (21, 18, 'Send Item Part Ack');
    end ;